name: First workflow

on:
  push:
    branches:
      - "main"
      - "develop"
      - "release"
jobs:
  lab-job:
    runs-on: ubuntu-latest
    steps:
      - name: Start job
        run: echo 'Hello DevOPs'
      - name: Second step
        run: echo 'Second steps'
  second-job:
    runs-on: ubuntu-latest
    needs: lab-job
    steps:
      - name: Start Second job
        run: echo 'Hello Second Job'
